# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# setups builds for linux on amd64
# https://goreleaser.com/customization/build
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "amd64"
    ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'

# creates SBOMs of all archives using syft
# https://goreleaser.com/customization/sbom
sboms:
  - artifacts: archive

# create release draft with the current tag, uploads artifacts and generates a changelog
# https://goreleaser.com/customization/release/
release:
  # If you want to manually examine the release before its live, uncomment this line:
  draft: true

# config the checksum filename
# https://goreleaser.com/customization/checksum
checksum:
  name_template: 'checksums.txt'

# config the snapshot name template when using the --snapshot flag
# https://goreleaser.com/customization/snapshots/
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
