name: Dagger Pipeline

on:
  push:
    branches:
      - "main"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  build-test-publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required for actions/checkout
      packages: write # This is required for publishing the package
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.2"
          cache: true

      - name: Run Dagger Pull Request
        if: github.event_name == 'pull_request'
        run: go run ci/dagger.go pull-request

      - name: Run Dagger Release
        if: startsWith(github.ref, 'refs/tags/')
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run ci/dagger.go release