name: Dagger Pipeline

on:
  push:
    branches:
      - "main"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

permissions:
  contents: write # This is required for actions/checkout
  packages: write # This is required for publishing the package

jobs:
  test-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.2"
          cache: true

      - name: Run Dagger Pull Request
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run ci/dagger.go pull-request


  publish-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.2"
          cache: true

      - name: Run Dagger Release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run ci/dagger.go release