name: Dagger Pipeline

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  build-test-publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout
      packages: write # This is required for publishing the package
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.2"
          cache: true

      - name: Run Dagger
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT: ${{ github.event_name }} 
        run: go run ci/dagger.go