name: Dagger Pull Request Pipeline

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'assets/**'

jobs:
  test-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.2"
          cache: true

      - name: Run Dagger Pull Request
        run: go run ci/dagger.go pull-request
